spring.application.name=SpringAI

spring.ai.openai.api-key=CREATE YOUR OWN API KEY AT OPEN ROUTER

spring.ai.openai.base-url=https://openrouter.ai/api/v1

spring.ai.openai.chat.model=openrouter/free

logging.level.org.springframework.ai=DEBUG
